### ISSUE TITLE
Misunderstanding the problems with room reverberation (RIR)

### ISSUE THREAD

**Issue by StuartIanNaylor** [OHF-Voice/wake-word-collective#11]
Misunderstanding the problems with room reverberation (RIR) and how easily they can be created

> Room Impulse Response (RIR) is an audio signal processing task that involves capturing and analyzing the acoustic characteristics of a room

https://ohf-voice.github.io/wake-word-collective/ 'the wake word while you walk around the room'

Its extremely hard (beamforming) to remove room impulse response, but very easy to create with many github projects to do this  https://github.com/LCAV/pyroomacoustics is one of many that can accurately add RIR
You only need <0.3m recordings that have very low RIR that can create many distances accurately with tools such as pyroomacoustics.

This allows you to provide datasets for certain devices as for a device with beamforming walking around a room including large RIR (large rooms) will greatly increase dataset entropy and resultant models will be less accurate as the beamforming will attenuate RIR.
Also any model created with samples containing RIR due to the nature of RIR sound will bounce off walls and arrive at the mic at different time periods due to differing distances.
These mix at the mic and the more distant the mic the more the recorded spectra will differ as more reverberation and mixing will happen creating very different harmonics.

At least if your recording at a distance supply metadata of that distance so a dataset can be filtered to only include near <0.3 recordings and also allow you to be sure you have an even spread than create dataset bias.

Metadata is hugely important, Recording Device, Recording distance, Gender, Age Band, Lang, Region (Reginal accents), is essential so that you can filter and create evenly spread datasets or tailor a dataset to a type of metadata for more accuracy.

From what I can see https://ohf-voice.github.io/wake-word-collective/ is going to create datasets only for devices without any form of RIR attenuation (beamforming and such) and create innacurate models as there is a limit to how much RIR you can include in samples as further distances to the mic in big rooms give big differences in spectra and greatly increasing dataset entropy and hence lowering model accuracy.

You can include a bit of RIR with non beamforming devices to increase accuracy of more distant wakewords but the tradeoff is overall accuracy and without the ability to filter too distant RIR for this type of device the dataset is pure potluck of what environment users submit.

Bemused as always.

Stuart

**Comment by StuartIanNaylor** [comment]
Common voice almost got things correct but failed in a few areas.
1... Meta data is crucial (recording device, record distance, gender, age group, Lang, region (accent), native speaker) all allow filtering to create balanced datasets. Even though none of the above is specific or private Common Voice failed to enforce and do has very little meta data.
2... Likely over enthusiasm of non native English speaking universities created a huge bias at least with the English dataset with a singular non native regional accent distinctly different to native speakers. Metadata filtering can fix this.
3... Validating recordings for some didn't work well as bad or wrong samples still exist.

Apart from that common voice gave a pretty much perfect way to collect speech sentences.
The only difference is here we are capturing words not sentences so on screen it should prompt for words.
Only a single dataset is needed for all types of keyword models and ! Keywords of the same voice are extremely important to some model types.
https://clagnut.com/blog/2380/#English_phonetic_pangrams
Phonetic tangrams are short sentences in any language that contain the distinct soundings of that language and make a great balanced !kwdataset that can be easily and quickly recorded especially interspersed with kw.

Having an open source keyword dataset of any keyword would allow many different model types to be created for different platforms. It does need meta data, ! Keywords and doesn't need distant recordings as they can be accurately recreated. https://github.com/DavidDiazGuerra/gpuRIR is another.


Also capturing KW @ the KWS is very easy as you are sampling that window and your KWS authenticates as does the subsequent actions of the smart speaker .
Having an option in after setting the metadata could quickly garner much data through use and provide the 1st open source dataset to get anywhere the volume and quality big data have without asking for option in.
On device recording hugely increases accuracy for datasets filtered for that device by it's metadata.
Command sentences for ASR also increase accuracy and can also be captured on device, again metadata is essential so correct balanced datasets can be created, by providing an opt-in and consent to share that will also collate through use

**Comment by balloob** [comment]
Thanks for the feedback

**Comment by StuartIanNaylor** [comment]
Just to check you did understand the 'feedback'. The way you are collating the current dataset will result in for most an inaccurate and relatively useless one.
Opensource has never had a comparative KW dataset comparative to bigdata.
To actually get an opensource iniative to collect a KW dataset but get it implemented wrong is extremely disheartening when the fixes are relatively easy to fix.
You can not include large RIR in a dataset hence why beamforming is such an important tech for smart speaker tech.
!KW of the same voice are also important and also the metadata to create even none skewed datasets.
The issue has been closed and brushed off as feedback whilst what you have will create a pretty useless dataset that could be fixed in a normal issue and reply manner
