### ISSUE TITLE
Language selection should be a drop-down list

### ISSUE THREAD

**Issue by jpbaril** [OHF-Voice/wake-word-collective#2]
Language list should be fixed (with maybe a "suggest additional language" field).
Otherwise you'll get multiple spelling variants and typos.
And what about regional/country language variations with their very different accents? Not having a proper language list will make it even harder to know how to indicate that in the field, and then obviously complex for you to understand which data sets belong to the same base language.

**Comment by mrdarrengriffin** [comment]
Hi @jpbaril

Whilst we have thought about doing this, a dropdown would introduce more friction since we would need to include all the languages and dialects.
