### ISSUE TITLE
Make indicator accessible to screen reader users

### ISSUE THREAD

**Issue by Nardol** [OHF-Voice/wake-word-collective#3]
When recording samples, we have to look for a visual indicator (a circle IIRC) to know when to start speaking.
I have not found how to know when to speak, nothing changes in the interface (Orca in my case) so I spoke randomly and read the counter to know if there was a recorded sample.

Could it be possible to add something which could be read by screen readers to allow E.G. blind users when to start each sample?

**Comment by mrdarrengriffin** [comment]
Hi @Nardol!

First of all, thank you for your patience in waiting for a reply to this issue.

I just wanted to reassure you that I am working to fix this by either adding an aria-label to the circle or adding a visual checkbox as an indicator to know when to speak. I expect it to get rolled out next week and I'd love to get your thoughts on if this works with your hardware.

**Comment by Nardol** [comment]
Nice, thanks for your answer and working on a fix. As soon as I know I can test, I will have a try and make a feedback.

**Comment by mrdarrengriffin** [comment]
Hi @Nardol

I was going to push this out with some other changes next week but thought I'd get the screen reader change out today. It should now tell you as soon as you are required to speak and when it's done capturing your voice.

I'm keen to get your feedback on this as I want all of our future websites and microsites to be accessible for all. For now, I will close the ticket but feel free to reply!

Thanks again!
