### ISSUE TITLE
Add audible cue to know when to speak

### ISSUE THREAD

**Issue by mrdarrengriffin** [OHF-Voice/wake-word-collective#9]
It can be difficult to know when to speak again after saying the wake word. Currently we only have a visual cue which is not helpful when the device is not in direct line of sight. 

**Potential solution**
Add an audible cue to indicate when to speak. 

**Potential knock-on issue**
Recordings may always include some reverb or echo from the audible cue which could skew the dataset

**Comment by balloob** [comment]
I don't think this will work, as we need just the background noise a bit before the user speaks the wake word.
